server {
    listen 80;
    server_name _;

    autoindex_exact_size off;
    autoindex_localtime on;

    location = / {
        try_files /index.html =404;
        root /usr/share/nginx/html;
    }

    location /ubuntu/ {
        alias /mirror/apt/mirror/archive.ubuntu.com/ubuntu/;
        autoindex on;
    }

    location /proxmox/ {
        alias /mirror/apt/mirror/download.proxmox.com/debian/pve/;
        autoindex on;
    }

    location /alma/ {
        alias /mirror/alma/;
        autoindex on;
    }

    location /arch/ {
        alias /mirror/arch/;
        autoindex on;
    }
}
